spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 745822442185310
            client-secret: 1420ee09ae2935be1bfdfee43f4f0890
scope: user_posts